boat_estimator: {

p0: [0.0,0.0,0.0],
vr0: [0.0,0.0,0.0],
euler0: [0.0,0.0,0.0],
vb0: [0.0,0.0,0.0],

sigma0: [100.0,  # pn
         100.0,  # pe
         100.0,  # pd
         10.0,  # vrn
         10.0,  # vre
         10.0,  # vrd
         360.0,  # psiDeg
         10.0,  # ub
         10.0,  # vb
         10.0],  # wb

sigmaProcess: [2.0,  # pn
               2.0,  # pe
               2.0,  # pd
               10.0,  # vrn
               10.0,  # vre
               10.0,  # vrd
               2.0,  # psi
               100.0,  # ub
               100.0,  # vb
               100.0],  # wb

sigmaInputs: [1.0,  #ax
              1.0,  #ay
              1.0,  #az
              1.0,  #p
              1.0,  #q
              1.0,  #r
              1.0,  #phi complimentary filter
              1.0],  #theta complimentary filter

sigmaGps: [0.4,     #horizontal
           0.7,     #vertical
           0.4,     #speed
           0.02,    #rtk horizontal
           0.04,    #rtk veritical
           0.02],   #rtk compass

sigmaApriltag: .1, # Apriltag xyz
apriltagID: 0,

compFiltKp: 0.3,
compFiltKi: 0.005,

# Old Offsets
#antennaOffset: [0.735,-0.851,-0.086], #mocap
#antennaOffset: [0.8,-0.62, 0.33],
#antennaOffset: [0.667387,-0.760626,0.356398], # Previous calibration w/ new arms
#antennaOffset: [0.74,-0.73,0.11], # Matts previous calibration
#antennaOffset: [0.76,-0.77,0.04],

# Current Offsets
#antennaOffset: [0.64,-0.78, 0.33], # Most recent calibration, hardware offset
antennaOffset: [0.0,0.0,0.0], # Offset for mocap
#antennaOffset: [0.0,0.0,-1.25], # Offset for simulation

cameraOffset: [0.0,0.0,0.116],
cameraRotation: [0.0,0.0,90.0], # roll, pitch, yaw

accelBias: [0.12,-0.07,0.28],
gyroBias: [0.0,0.0,0.0]
}

