boat_estimator: {

p0: [0.0,0.0,0.0],
vr0: [0.0,0.0,0.0],
euler0: [0.0,0.0,0.0],
vb0: [0.0,0.0,0.0],

sigma0: [100.0,  # pn
         100.0,  # pe
         100.0,  # pd
         10.0,  # vrn
         10.0,  # vre
         10.0,  # vrd
         360.0,  # psiDeg
         10.0,  # ub
         10.0,  # vb
         10.0],  # wb

sigmaProcess: [2.0,  # pn
               2.0,  # pe
               2.0,  # pd
               10.0,  # vrn
               10.0,  # vre
               10.0,  # vrd
               2.0,  # psi
               10.0,  # ub #TODO: These seem a little high.  Maybe there is somethign wrong that makes them be so high?
               10.0,  # vb
               10.0],  # wb

sigmaInputs: [1.0,  #ax
              1.0,  #ay
              1.0,  #az
              1.0,  #p
              1.0,  #q
              1.0,  #r
              1.0,  #phi complimentary filter
              1.0],  #theta complimentary filter

sigmaGps: [0.4,     #horizontal
           0.7,     #vertical
           0.4,     #speed
           0.02,    #rtk horizontal
           0.04,    #rtk veritical
           0.02],   #rtk compass

compFiltKp: 0.1,

}

